kind: Component

transformers:
- sas-activities-transformers.yaml
- sas-analytics-events-transformers.yaml
- sas-analytics-execution-transformers.yaml
- sas-analytics-resources-transformers.yaml
- sas-analytics-services-transformers.yaml
- sas-annotations-transformers.yaml
- sas-app-registry-transformers.yaml
- sas-audit-transformers.yaml
- sas-authorization-transformers.yaml
- sas-batch-transformers.yaml
- sas-business-rules-services-transformers.yaml
- sas-cas-control-transformers.yaml
- sas-catalog-services-transformers.yaml
- sas-category-execution-provider-transformers.yaml
- sas-category-taxonomy-transformers.yaml
- sas-code-debugger-transformers.yaml
- sas-code-debugger-app-transformers.yaml
- sas-comments-transformers.yaml
- sas-compute-transformers.yaml
- sas-concept-execution-provider-transformers.yaml
- sas-config-reconciler-transformers.yaml
- sas-configuration-transformers.yaml
- sas-connect-transformers.yaml
- sas-credentials-transformers.yaml
- sas-crossdomainproxy-transformers.yaml
- sas-data-agent-server-colocated-transformers.yaml
- sas-data-agent-services-transformers.yaml
- sas-data-explorer-app-transformers.yaml
- sas-data-flows-transformers.yaml
- sas-data-mining-transformers.yaml
- sas-data-mining-models-transformers.yaml
- sas-data-mining-project-resources-transformers.yaml
- sas-data-mining-results-transformers.yaml
- sas-data-mining-risk-models-transformers.yaml
- sas-data-plans-transformers.yaml
- sas-data-quality-services-transformers.yaml
- sas-data-sources-transformers.yaml
- sas-data-studio-app-transformers.yaml
- sas-decision-manager-app-transformers.yaml
- sas-decisions-definitions-transformers.yaml
- sas-decisions-runtime-builder-transformers.yaml
- sas-deployment-data-transformers.yaml
- sas-device-management-transformers.yaml
- sas-discovery-services-transformers.yaml
- sas-documents-transformers.yaml
- sas-drive-transformers.yaml
- sas-drive-app-transformers.yaml
- sas-environment-manager-app-transformers.yaml
- sas-event-monitor-transformers.yaml
- sas-event-stream-manager-app-transformers.yaml
- sas-event-stream-processing-metering-app-transformers.yaml
- sas-event-stream-processing-streamviewer-app-transformers.yaml
- sas-event-stream-processing-studio-app-transformers.yaml
- sas-feature-flags-transformers.yaml
- sas-files-transformers.yaml
- sas-folders-transformers.yaml
- sas-fonts-transformers.yaml
- sas-forecasting-comparison-transformers.yaml
- sas-forecasting-data-definition-transformers.yaml
- sas-forecasting-events-transformers.yaml
- sas-forecasting-exploration-transformers.yaml
- sas-forecasting-filters-transformers.yaml
- sas-forecasting-gateway-transformers.yaml
- sas-forecasting-models-transformers.yaml
- sas-forecasting-overrides-transformers.yaml
- sas-forecasting-pipelines-transformers.yaml
- sas-formats-transformers.yaml
- sas-geo-enrichment-transformers.yaml
- sas-graph-builder-app-transformers.yaml
- sas-graph-templates-transformers.yaml
- sas-identities-transformers.yaml
- sas-import-9-transformers.yaml
- sas-information-catalog-app-transformers.yaml
- sas-insights-transformers.yaml
- sas-job-execution-transformers.yaml
- sas-job-execution-app-transformers.yaml
- sas-job-flow-scheduling-transformers.yaml
- sas-launcher-transformers.yaml
- sas-lineage-app-transformers.yaml
- sas-links-transformers.yaml
- sas-list-data-transformers.yaml
- sas-localization-transformers.yaml
- sas-logon-app-transformers.yaml
- sas-mail-transformers.yaml
- sas-maps-transformers.yaml
- sas-microanalytic-score-transformers.yaml
- sas-ml-pipeline-automation-transformers.yaml
- sas-model-management-transformers.yaml
- sas-model-manager-app-transformers.yaml
- sas-model-publish-transformers.yaml
- sas-model-repository-transformers.yaml
- sas-model-studio-app-transformers.yaml
- sas-natural-language-generation-transformers.yaml
- sas-notifications-transformers.yaml
- sas-office-addin-app-transformers.yaml
- sas-parse-execution-provider-transformers.yaml
- sas-preferences-transformers.yaml
- sas-report-distribution-transformers.yaml
- sas-report-execution-transformers.yaml
- sas-report-images-transformers.yaml
- sas-report-operations-transformers.yaml
- sas-report-renderer-transformers.yaml
- sas-report-services-group-transformers.yaml
- sas-scheduler-transformers.yaml
- sas-score-definitions-transformers.yaml
- sas-score-execution-transformers.yaml
- sas-search-transformers.yaml
- sas-sentiment-execution-provider-transformers.yaml
- sas-studio-transformers.yaml
- sas-studio-app-transformers.yaml
- sas-studio-development-transformers.yaml
- sas-subject-contacts-transformers.yaml
- sas-templates-transformers.yaml
- sas-terms-management-transformers.yaml
- sas-text-analytics-transformers.yaml
- sas-text-analytics-execution-transformers.yaml
- sas-text-analytics-provider-transformers.yaml
- sas-text-concepts-transformers.yaml
- sas-theme-content-transformers.yaml
- sas-theme-designer-app-transformers.yaml
- sas-themes-transformers.yaml
- sas-thumbnails-transformers.yaml
- sas-topic-execution-provider-transformers.yaml
- sas-topic-management-transformers.yaml
- sas-transfer-transformers.yaml
- sas-transformations-transformers.yaml
- sas-types-transformers.yaml
- sas-visual-analytics-transformers.yaml
- sas-visual-analytics-administration-transformers.yaml
- sas-visual-analytics-app-transformers.yaml
- sas-web-data-access-transformers.yaml
- sas-webhooks-transformers.yaml
- sas-workflow-transformers.yaml
- sas-workflow-definition-history-transformers.yaml
- sas-workflow-manager-app-transformers.yaml
- sas-workload-orchestrator-transformers.yaml
- sas-certframe-transformers.yaml

configurations:
- sas-certframe-configurations.yaml
