resources:
- sas-activities/
- sas-admin-content-loader/
- sas-analytics-events/
- sas-analytics-execution/
- sas-analytics-resources/
- sas-analytics-services/
- sas-annotations/
- sas-app-registry/
- sas-arke/
- sas-audit/
- sas-authorization/
- sas-backup-job/
- sas-batch/
- sas-business-rules-services/
- sas-cas-control/
- sas-cas-operator/
- sas-catalog-services/
- sas-category-execution-provider/
- sas-category-taxonomy/
- sas-certframe/
- sas-code-debugger/
- sas-code-debugger-app/
- sas-comments/
- sas-commonfiles/
- sas-compute/
- sas-concept-execution-provider/
- sas-concept-taxonomy/
- sas-config-reconciler/
- sas-configuration/
- sas-connect/
- sas-connect-spawner/
- sas-consul-server/
- sas-credentials/
- sas-crossdomainproxy/
- sas-crunchy5-postgres-operator/
- sas-data-agent-server-colocated/
- sas-data-agent-server-tenant/
- sas-data-agent-services/
- sas-data-explorer-app/
- sas-data-flows/
- sas-data-mining/
- sas-data-mining-models/
- sas-data-mining-project-resources/
- sas-data-mining-results/
- sas-data-mining-risk-models/
- sas-data-plans/
- sas-data-quality-services/
- sas-data-server-operator/
- sas-data-sources/
- sas-data-studio-app/
- sas-decision-manager-app/
- sas-decisions-definitions/
- sas-decisions-runtime-builder/
- sas-deployment-data/
- sas-device-management/
- sas-discovery-services/
- sas-documents/
- sas-drive/
- sas-drive-app/
- sas-environment-manager-app/
- sas-esp-operator/
- sas-event-monitor/
- sas-event-stream-manager-app/
- sas-event-stream-processing-metering-app/
- sas-event-stream-processing-streamviewer-app/
- sas-event-stream-processing-studio-app/
- sas-feature-flags/
- sas-files/
- sas-folders/
- sas-fonts/
- sas-forecasting-comparison/
- sas-forecasting-data-definition/
- sas-forecasting-events/
- sas-forecasting-exploration/
- sas-forecasting-filters/
- sas-forecasting-gateway/
- sas-forecasting-models/
- sas-forecasting-overrides/
- sas-forecasting-pipelines/
- sas-formats/
- sas-geo-enrichment/
- sas-graph-builder-app/
- sas-graph-templates/
- sas-identities/
- sas-import-9/
- sas-import-data-loader/
- sas-information-catalog-app/
- sas-insights/
- sas-inventory-collector/
- sas-job-execution/
- sas-job-execution-app/
- sas-job-flow-scheduling/
- sas-k8s-common/
- sas-launcher/
- sas-lineage-app/
- sas-links/
- sas-list-data/
- sas-localization/
- sas-logon-app/
- sas-mail/
- sas-maps/
- sas-microanalytic-score/
- sas-ml-pipeline-automation/
- sas-model-management/
- sas-model-manager-app/
- sas-model-publish/
- sas-model-repository/
- sas-model-studio-app/
- sas-natural-language-generation/
- sas-notifications/
- sas-office-addin-app/
- sas-opendistro-operator/
- sas-parse-execution-provider/
- sas-preferences/
- sas-prepull/
- sas-process-exporter/
- sas-programming-environment/
- sas-pyconfig/
- sas-quality-knowledge-base/
- sas-rabbitmq-server/
- sas-readiness/
- sas-redis-operator/
- sas-redis-server/
- sas-report-distribution/
- sas-report-execution/
- sas-report-images/
- sas-report-operations/
- sas-report-renderer/
- sas-report-services-group/
- sas-restore-job/
- sas-scheduler/
- sas-score-definitions/
- sas-score-execution/
- sas-search/
- sas-sentiment-execution-provider/
- sas-studio/
- sas-studio-app/
- sas-studio-development/
- sas-subject-contacts/
- sas-templates/
- sas-terms-management/
- sas-text-analytics/
- sas-text-analytics-execution/
- sas-text-analytics-provider/
- sas-text-concepts/
- sas-theme-content/
- sas-theme-designer-app/
- sas-themes/
- sas-thumbnails/
- sas-topic-execution-provider/
- sas-topic-management/
- sas-transfer/
- sas-transformations/
- sas-types/
- sas-visual-analytics/
- sas-visual-analytics-administration/
- sas-visual-analytics-app/
- sas-web-data-access/
- sas-webhooks/
- sas-workflow/
- sas-workflow-definition-history/
- sas-workflow-manager-app/
- sas-workload-orchestrator/

generators:
- configmaps.yaml