resources:
- components/sas-activities/
- components/sas-analytics-events/
- components/sas-analytics-execution/
- components/sas-analytics-resources/
- components/sas-analytics-services/
- components/sas-annotations/
- components/sas-app-registry/
- components/sas-audit/
- components/sas-authorization/
- components/sas-batch/
- components/sas-business-rules-services/
- components/sas-cas-control/
- components/sas-catalog-services/
- components/sas-category-execution-provider/
- components/sas-category-taxonomy/
- components/sas-code-debugger/
- components/sas-code-debugger-app/
- components/sas-comments/
- components/sas-compute/
- components/sas-concept-execution-provider/
- components/sas-concept-taxonomy/
- components/sas-config-reconciler/
- components/sas-configuration/
- components/sas-connect/
- components/sas-credentials/
- components/sas-crossdomainproxy/
- components/sas-data-agent-server-colocated/
- components/sas-data-agent-services/
- components/sas-data-explorer-app/
- components/sas-data-flows/
- components/sas-data-mining/
- components/sas-data-mining-models/
- components/sas-data-mining-project-resources/
- components/sas-data-mining-results/
- components/sas-data-mining-risk-models/
- components/sas-data-plans/
- components/sas-data-quality-services/
- components/sas-data-sources/
- components/sas-data-studio-app/
- components/sas-decision-manager-app/
- components/sas-decisions-definitions/
- components/sas-decisions-runtime-builder/
- components/sas-deployment-data/
- components/sas-device-management/
- components/sas-discovery-services/
- components/sas-documents/
- components/sas-drive/
- components/sas-drive-app/
- components/sas-environment-manager-app/
- components/sas-event-monitor/
- components/sas-event-stream-manager-app/
- components/sas-event-stream-processing-metering-app/
- components/sas-event-stream-processing-streamviewer-app/
- components/sas-event-stream-processing-studio-app/
- components/sas-feature-flags/
- components/sas-files/
- components/sas-folders/
- components/sas-fonts/
- components/sas-forecasting-comparison/
- components/sas-forecasting-data-definition/
- components/sas-forecasting-events/
- components/sas-forecasting-exploration/
- components/sas-forecasting-filters/
- components/sas-forecasting-gateway/
- components/sas-forecasting-models/
- components/sas-forecasting-overrides/
- components/sas-forecasting-pipelines/
- components/sas-formats/
- components/sas-geo-enrichment/
- components/sas-graph-builder-app/
- components/sas-graph-templates/
- components/sas-identities/
- components/sas-import-9/
- components/sas-information-catalog-app/
- components/sas-insights/
- components/sas-job-execution/
- components/sas-job-execution-app/
- components/sas-job-flow-scheduling/
- components/sas-launcher/
- components/sas-lineage-app/
- components/sas-links/
- components/sas-list-data/
- components/sas-localization/
- components/sas-logon-app/
- components/sas-mail/
- components/sas-maps/
- components/sas-microanalytic-score/
- components/sas-ml-pipeline-automation/
- components/sas-model-management/
- components/sas-model-manager-app/
- components/sas-model-publish/
- components/sas-model-repository/
- components/sas-model-studio-app/
- components/sas-natural-language-generation/
- components/sas-notifications/
- components/sas-office-addin-app/
- components/sas-parse-execution-provider/
- components/sas-preferences/
- components/sas-report-distribution/
- components/sas-report-execution/
- components/sas-report-images/
- components/sas-report-operations/
- components/sas-report-renderer/
- components/sas-report-services-group/
- components/sas-scheduler/
- components/sas-score-definitions/
- components/sas-score-execution/
- components/sas-search/
- components/sas-sentiment-execution-provider/
- components/sas-studio/
- components/sas-studio-app/
- components/sas-studio-development/
- components/sas-subject-contacts/
- components/sas-templates/
- components/sas-terms-management/
- components/sas-text-analytics/
- components/sas-text-analytics-execution/
- components/sas-text-analytics-provider/
- components/sas-text-concepts/
- components/sas-theme-content/
- components/sas-theme-designer-app/
- components/sas-themes/
- components/sas-thumbnails/
- components/sas-topic-execution-provider/
- components/sas-topic-management/
- components/sas-transfer/
- components/sas-transformations/
- components/sas-types/
- components/sas-visual-analytics/
- components/sas-visual-analytics-administration/
- components/sas-visual-analytics-app/
- components/sas-web-data-access/
- components/sas-webhooks/
- components/sas-workflow/
- components/sas-workflow-definition-history/
- components/sas-workflow-manager-app/
- components/sas-workload-orchestrator/
generators:
- configmaps.yaml
vars:
- name: INGRESS_HOST
  objref:
    kind: ConfigMap
    name: ingress-input
    apiVersion: v1
  fieldref:
    fieldpath: data.INGRESS_HOST